timezone: Asia/Shanghai
output_dir: docs/daily
days_to_keep_seen: 30
since_hours: 24

max_items:
  per_feed: 5
  per_arxiv: 10
  arena_top_n: 20

sections:

  - key: vendor_global
    title: 官方 / 厂商 · 国外
    includes: [vendor-global]

  - key: media_zh
    title: 中文媒体
    includes: [zh-media]

  - key: media_en
    title: 英文媒体 / Newsletter
    includes: [en-news, en-depth, newsletter]

  - key: research
    title: 研究机构 / 开源社区
    includes: [research-lab, open-source]

  - key: arxiv
    title: 论文 · arXiv
    includes: [arxiv]

feeds:
  # —— 中文媒体 ——
  - name: 机器之心
    url: https://www.jiqizhixin.com/rss
    category: zh-media
  - name: 量子位
    url: https://www.qbitai.com/feed
    category: zh-media
  - name: 极客公园
    url: https://www.geekpark.net/rss
    category: zh-media
  - name: 少数派
    url: https://sspai.com/feed
    category: zh-media

  # —— 英文媒体 / Newsletter ——
  - name: Latent Space
    url: https://www.latent.space/feed
    category: en-depth
  - name: Semianalysis
    url: https://www.semianalysis.com/feed
    category: en-depth

  # —— 研究机构 ——
  - name: Microsoft Research
    url: https://www.microsoft.com/en-us/research/feed/
    category: research-lab
  - name: Apple ML Research (experimental)
    url: https://machinelearning.apple.com/rss.xml
    category: research-lab

  # —— 开源社区 ——
  - name: Hugging Face Blog
    url: https://huggingface.co/blog/feed.xml
    category: open-source
  - name: EleutherAI · Blog
    url: https://blog.eleuther.ai/feed.xml
    category: open-source

cn
    
# ——（国外）厂商 ——
  - name: OpenAI · Status
    url: https://status.openai.com/history.rss
    category: vendor-global
  - name: Anthropic · Status
    url: https://status.anthropic.com/history.rss
    category: vendor-global
  - name: NVIDIA Technical Blog
    url: https://blogs.nvidia.com/feed/
    category: vendor-global
  - name: AWS Machine Learning · Blog
    url: https://aws.amazon.com/blogs/machine-learning/feed/
    category: vendor-global


arxiv:
  - name: LLM core
    query: (ti:"large language model" OR ti:LLM OR abs:"large language model" OR abs:LLM) AND (cat:cs.CL OR cat:cs.LG OR cat:cs.AI OR cat:stat.ML)
    max_results: 25
  - name: MoE & Reasoning
    query: (ti:"mixture of experts" OR abs:"mixture of experts" OR ti:reasoning OR abs:reasoning OR ti:distillation OR abs:distillation) AND (cat:cs.CL OR cat:cs.LG OR cat:cs.AI OR cat:stat.ML)
    max_results: 25

  
