timezone: Asia/Shanghai
output_dir: docs/daily
days_to_keep_seen: 30
since_hours: 24

max_items:
  per_feed: 5
  per_arxiv: 10
  arena_top_n: 20

sections:
  - key: vendor_cn
    title: 官方 / 厂商 · 国内
    includes: [vendor-cn]

  - key: vendor_global
    title: 官方 / 厂商 · 国外
    includes: [vendor-global]

  - key: media_zh
    title: 中文媒体
    includes: [zh-media]

  - key: media_en
    title: 英文媒体 / Newsletter
    includes: [en-news, en-depth, newsletter]

  - key: research
    title: 研究机构 / 开源社区
    includes: [research-lab, open-source]

  - key: arxiv
    title: 论文 · arXiv
    includes: [arxiv]

feeds:
  # —— 中文媒体 ——
  - name: 机器之心
    url: https://www.jiqizhixin.com/rss
    category: zh-media
  - name: 量子位
    url: https://www.qbitai.com/feed
    category: zh-media
  - name: 极客公园
    url: https://www.geekpark.net/rss
    category: zh-media
  - name: 少数派
    url: https://sspai.com/feed
    category: zh-media
  - name: InfoQ 中文
    url: https://feeds.infoq.com/cn
    category: zh-media

  # —— 英文媒体 / Newsletter ——
  - name: Ben's Bites
    url: https://www.bensbites.co/feed
    category: newsletter
  - name: The Rundown AI
    url: https://www.therundown.ai/feed
    category: newsletter
  - name: Last Week in AI
    url: https://www.lastweekin.ai/feed
    category: en-news
  - name: Latent Space
    url: https://www.latent.space/feed
    category: en-depth
  - name: Semianalysis
    url: https://www.semianalysis.com/feed
    category: en-depth

  # —— 研究机构 ——
  - name: Google AI Blog
    url: https://ai.googleblog.com/feeds/posts/default
    category: research-lab
  - name: DeepMind
    url: https://deepmind.google/rss.xml
    category: research-lab
  - name: Microsoft Research
    url: https://www.microsoft.com/en-us/research/feed/
    category: research-lab
  - name: Apple ML Research (experimental)
    url: https://machinelearning.apple.com/rss.xml
    category: research-lab

  # —— 开源社区 ——
  - name: Hugging Face Blog
    url: https://huggingface.co/blog/feed.xml
    category: open-source
  - name: LAION · Blog
    url: https://laion.ai/blog/index.xml
    category: open-source
  - name: EleutherAI · Blog
    url: https://blog.eleuther.ai/feed.xml
    category: open-source
  # 可选：OpenMMLab（如需）
  # - name: OpenMMLab · Blog
  #   url: https://openmmlab.com/blog/index.xml
  #   category: open-source

  # —— 厂商（国内） ——
  - name: Qwen 通义千问 · Blog
    url: https://qwenlm.ai/blog/index.xml
    category: vendor-cn
  - name: 百川智能 Baichuan · Blog
    url: https://www.baichuan-ai.com/blog/index.xml
    category: vendor-cn
  - name: 智谱 AI · 新闻
    url: https://www.zhipuai.cn/news/index.xml
    category: vendor-cn
  - name: 华为云开发者 · 博客
    url: https://bbs.huaweicloud.com/rss/blogs
    category: vendor-cn
  - name: 飞桨 PaddlePaddle · 官方博客
    url: https://blog.paddlepaddle.org.cn/feed/
    category: vendor-cn
  - name: 火山引擎 Volcengine · 博客 (experimental)
    url: https://www.volcengine.com/feed
    category: vendor-cn
  # 微信公众号可用 RSSHub（可选）
  # - name: 百度智能云 · 公众号（RSSHub）
  #   url: https://rsshub.app/wechat/official-account/BaiduCloudAI
  #   category: vendor-cn
  # - name: 阿里云 · 公众号（RSSHub）
  #   url: https://rsshub.app/wechat/official-account/aliyun
  #   category: vendor-cn
  # - name: 腾讯云 · 公众号（RSSHub）
  #   url: https://rsshub.app/wechat/official-account/qcloudxiaoyun
  #   category: vendor-cn

arxiv:
  - name: LLM core
    query: (ti:"large language model" OR ti:LLM OR abs:"large language model" OR abs:LLM) AND (cat:cs.CL OR cat:cs.LG OR cat:cs.AI OR cat:stat.ML)
    max_results: 25
  - name: MoE & Reasoning
    query: (ti:"mixture of experts" OR abs:"mixture of experts" OR ti:reasoning OR abs:reasoning OR ti:distillation OR abs:distillation) AND (cat:cs.CL OR cat:cs.LG OR cat:cs.AI OR cat:stat.ML)
    max_results: 25

leaderboards:
  chatbot_arena_elo_json: https://lmsys.org/arena/elo.json
  
